export const Baralho = [
  {
    id: 1,
    name: "Virua A",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 1,
  },
  {
    id: 2,
    name: "Virua B",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 2,
  },
  {
    id: 3,
    name: "Virua C",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 3,
  },
  {
    id: 4,
    name: "Virua D",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 4,
  },
  {
    id: 5,
    name: "Virua A",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 1,
  },
  {
    id: 6,
    name: "Virua B",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 2,
  },
  {
    id: 7,
    name: "Virua C",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 3,
  },
  {
    id: 8,
    name: "Virua D",
    imgUrl: "https://via.placeholder.com/364x510",
    turned: false,
    value: 4,
  },
];
